org: ajaypatel
app: rsvp
service: rsvp
frameworkVersion: "3"

provider:
    name: aws
    runtime: nodejs18.x
    profile: ajay
    logs:
        http: false

plugins:
    - serverless-offline
    - serverless-dotenv-plugin
    - serverless-middleware

functions:
    welcome:
        handler: index.handler
        events:
            - http:
                  path: /healthcheck
                  method: GET
                  cors: true
    UserCreate:
        handler: handlers/user/register.handler
        events:
            - http:
                  path: /user
                  method: POST
                  cors: true
    UserLogin:
        handler: handlers/user/login.handler
        events:
            - http:
                  path: /login
                  method: POST
                  cors: true
    UserLogout:
        handler: handlers/user/logout.handler
        middleware:
            pre:
                - middleware/auth.authenticate
        events:
            - http:
                  path: /logout
                  method: POST
                  cors: true
# resources:
#     Resources:
#         MyBucket:
#             Type: AWS::S3::Bucket
#             Properties:
#                 BucketName: myrsvp-bucket
