service: rsvp
frameworkVersion: "3"

provider:
    name: aws
    runtime: nodejs18.x

functions:
    api:
        handler: src/index.handler
        events:
            - httpApi: "*"

plugins:
    - serverless-offline
    - serverless-dotenv-plugin
