service: rsvp
frameworkVersion: "3"

provider:
    name: aws
    runtime: nodejs18.x
    iamRoleStatements:
      - Effect: Allow
        Action: 
            - s3:*
            - ses:*
    
functions:
    api:
        handler: src/index.handler
        events:
            - httpApi: "*"

plugins:
    - serverless-offline
    - serverless-dotenv-plugin
