org: ajaypatel
app: rsvp
service: rsvp
frameworkVersion: "4"

provider:
    name: aws
    runtime: nodejs18.x
    profile: ajay
    iamRoleStatements:
        - Effect: Allow
          Action:
              - s3:*
              - ses:*
          Resource: "*"
    logs:
        http: true

plugins:
    - serverless-offline
    - serverless-dotenv-plugin
    - serverless-middleware
    - serverless-domain-manager

custom:
    customDomain:
        domainName: rsvp-backend.ajayproject.com
        basePath: ""
        stage: dev
        createRoute53Records: true

functions:
    welcome:
        handler: index.handler
        events:
            - http:
                  path: /healthcheck
                  method: GET
                  cors: true
    UserCreate:
        handler: handlers/user/register.handler
        events:
            - http:
                  path: /user
                  method: POST
                  cors: true
    GetUser:
        handler: handlers/user/user.handler
        middleware:
            pre:
                - middleware/auth.authenticate
        events:
            - http:
                  path: /user
                  method: GET
                  cors: true
    UserLogin:
        handler: handlers/user/login.handler
        events:
            - http:
                  path: /login
                  method: POST
                  cors: true
    UserLogout:
        handler: handlers/user/logout.handler
        middleware:
            pre:
                - middleware/auth.authenticate
        events:
            - http:
                  path: /logout
                  method: POST
                  cors: true
